version: '3'

services:
 chat:
   build:
     context: .
     args:
       NODE_ENVIRONMENT: prod
       PORT: 3000
       HOST: 0.0.0.0
   environment:
     NODE_ENVIRONMENT: prod
   command: npm start
   ports:
     - 3000:3000
   volumes:
     - .:/usr/app
    
 ngrok:
   image: wernight/ngrok
   volumes:
     - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
   ports:
     - "4040:4040"
   command: ["ngrok", "http", "3000"]