version: '3'

services:
 chat:
   build:
     context: .
     args:
       PORT: 3000
   command: npm start
   ports:
     - 3000:3000
   volumes:
     - .:/usr/app

 ngrok:
   image: shkoliar/ngrok:latest      
   ports:
      - '4040:4040'
   links:
      - chat
   environment:
      - PARAMS=http -region=eu -authtoken=2YgVJeV2bBTjlWujVzbn80M8iIu_6G8zE9k7HgPYmStMdthXo chat:3000