version: '2'

services:
 chat:
   build:
     context: .
     args:
       PORT: 3000
   command: npm start
   ports:
     - 3000:3000

 ngrok:
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
